// <auto-generated />
using EcoFarmAdmin;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcoFarmAdmin.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20221205173140_AddedTrees")]
    partial class AddedTrees
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("EcoFarmAdmin.Domain.DevObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DevObjects");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("EcoFarmAdmin.Domain.Product", b =>
                {
                    b.HasBaseType("EcoFarmAdmin.Domain.DevObject");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("EcoFarmAdmin.Domain.Tree", b =>
                {
                    b.HasBaseType("EcoFarmAdmin.Domain.DevObject");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("ProductId");

                    b.ToTable("Trees");
                });

            modelBuilder.Entity("EcoFarmAdmin.Domain.Product", b =>
                {
                    b.HasOne("EcoFarmAdmin.Domain.DevObject", null)
                        .WithOne()
                        .HasForeignKey("EcoFarmAdmin.Domain.Product", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EcoFarmAdmin.Domain.Tree", b =>
                {
                    b.HasOne("EcoFarmAdmin.Domain.DevObject", null)
                        .WithOne()
                        .HasForeignKey("EcoFarmAdmin.Domain.Tree", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcoFarmAdmin.Domain.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
